version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)  # Generate dynamic tag
      - export IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo "REPOSITORY_URI: $REPOSITORY_URI"
      - echo "IMAGE_URI: $IMAGE_URI"

  build:
    commands:
      - echo "Building the Docker image with tag: $IMAGE_URI"
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ECR..."
      - docker push $IMAGE_URI
      - echo "Writing image definitions file..."
      - printf '[{"name":"nodejs-container","imageUri":"%s"}]\n' "$IMAGE_URI" > imagedefinitions.json
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster nodejs-cluster --service nodejs-service --force-new-deployment

artifacts:
  files:
    - imagedefinitions.json
